name: Dependencies

on:
  push:
    branches: ["main"]
    # Push events to every tag not containing /
    tags: ["*"]
  pull_request:
    branches: ["main"]

env:
  ANDROID_LIB_HOME: ${{ github.workspace }}/Libraries

# to upload build-artifacts to a release
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-20.04
    container: ghcr.io/eeg-digitizar/deps-builder:main
    strategy:
      matrix:
        buildtype: [Debug, Release, RelWithDebInfo, MinSizeRel]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Boost
        run: ./build_boost.sh ${{ matrix.buildtype }} > build_boost.log && rm -rf "Boost-for-Android"

      - name: Build fmt
        run: ./build_fmt.sh ${{ matrix.buildtype }} > build_fmt.log && rm -rf "fmtlib"

      - name: Build Eigen
        run: ./build_eigen.sh ${{ matrix.buildtype }} > build_eigen.log && rm -rf "eigen-3.4.0"

      - name: Build FreeImage
        run: ./build_freeimage.sh ${{ matrix.buildtype }} > build_freeimage.log && rm -rf "FreeImage"

      - name: Build glog
        run: ./build_glog.sh ${{ matrix.buildtype }} > build_glog.log && rm -rf "glog"

      - name: Build libyuv
        run: ./build_libyuv.sh ${{ matrix.buildtype }} > build_libyuv.log && rm -rf "glog"

      - name: Build Ceres
        run: ./build_ceres.sh ${{ matrix.buildtype }} > build_ceres.log && rm -rf "ceres-solver-2.0.0"

      - name: Build COLMAP
        run: ./build_colmap.sh ${{ matrix.buildtype }} > build_colmap.log && rm -rf "colmap"

      - name: Zip Dependencies
        run: zip -r Libraries-${{ matrix.buildtype }}.zip Libraries

      - name: Zip Build Logs
        run: zip -r Buildlogs-${{ matrix.buildtype }}.zip build_*.log

      - name: Upload Dependencies to artifacts
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Libraries
          path: Libraries-${{ matrix.buildtype }}.zip
          if-no-files-found: error
          retention-days: 90

      - name: Upload Build Logs to artifacts
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Build Logs
          path: Buildlogs-${{ matrix.buildtype }}.zip
          if-no-files-found: error
          retention-days: 90

  release:
    needs: build
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          path: ${{ github.workspace }}

      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          body: "Prebuilt DigitizAR Dependencies and OpenCV Android SDK with contrib modules"
          file: ${{ github.workspace }}/Libraries/*
          file_glob: true
