name: Dependencies

on:
  schedule:
    # run every 90 days (artifacts get deleted then)
    - cron: 1 1 1 3,6,9,12 *
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  ANDROID_LIB_HOME: ${{ github.workspace }}/Libraries

jobs:
  build:
    runs-on: ubuntu-20.04
    container: ghcr.io/eeg-digitizar/deps-builder:main
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Boost
        run: ./build_boost.sh Debug Release > build_boost.log && rm -rf "Boost-for-Android"

      - name: Build fmt
        run: ./build_fmt.sh Debug Release > build_fmt.log && rm -rf "fmtlib"

      - name: Build Eigen
        run: ./build_eigen.sh Debug Release > build_eigen.log && rm -rf "eigen-3.4.0"

      - name: Build FreeImage
        run: ./build_freeimage.sh Debug Release > build_freeimage.log && rm -rf "FreeImage"

      - name: Build glog
        run: ./build_glog.sh Debug Release > build_glog.log && rm -rf "glog"

      - name: Build Ceres
        run: ./build_ceres.sh Debug Release > build_ceres.log && rm -rf "ceres-solver-2.0.0"

      - name: Build COLMAP
        run: ./build_colmap.sh Debug Release > build_colmap.log && rm -rf "colmap"

      - name: Zip DigitizAR-Dependencies
        run: zip -r Libraries.zip Libraries

      - name: Upload DigitizAR-Dependencies
        uses: actions/upload-artifact@v3.1.0
        with:
          name: DigitizAR-Dependencies
          path: ${{github.workspace}}/Libraries.zip
          if-no-files-found: error
          retention-days: 90

      - name: Upload Build Logs
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Build Logs
          path: ${{github.workspace}}/build_*.log
          if-no-files-found: error
          retention-days: 90
